"use client";

import { useEffect, useState } from "react";
import { FileText, Copy, Download, Check, ShieldCheck } from "lucide-react";
import { Badge } from "@/components/ui/Badge";
import { Button } from "@/components/ui/Button";
import { GlassCard } from "@/components/ui/Card";
import {
  RiskScoreCard,
  ScamTypeCard,
  ConfidenceCard,
  RedFlagsCard,
  EnglishExplanationCard,
  UrduExplanationCard,
  SafeActionsCard,
  DoNotDoCard,
  AttackChainCard,
  PrivacyWarningCard,
} from "@/components/analyzer/ResultCards";
import { analyzeText } from "@/lib/analyzeText";
import { DEMO_WHATSAPP } from "@/data/dummyData";
import { getReportFromSession, generateReportId, buildReportText } from "@/lib/reportStore";

// Used only when the Report page is opened directly (e.g. a fresh tab)
// without a saved analysis in this browser session — keeps the page
// demoable on its own. TODO(Mohsin): once /api/analyze exists, this whole
// fallback branch can be removed in favor of always loading a real report.
function buildFallbackReport() {
  return {
    ...analyzeText(DEMO_WHATSAPP.text),
    scannedText: DEMO_WHATSAPP.text,
    generatedAt: new Date().toISOString(),
  };
}

export function ReportView() {
  const [report, setReport] = useState(null);
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    const saved = getReportFromSession();
    setReport(saved || buildFallbackReport());
  }, []);

  if (!report) {
    return (
      <div className="max-w-5xl mx-auto px-5 md:px-8 py-14 md:py-20">
        <Badge tone="cyan">
          <FileText className="w-3.5 h-3.5" /> Report
        </Badge>
        <h1 className="mt-5 text-3xl md:text-5xl font-bold text-white tracking-tight">
          Official Safety Analysis Report
        </h1>
        <GlassCard className="mt-8 p-6 h-[92px] animate-pulse" />
        <GlassCard className="mt-6 p-6 h-[96px] animate-pulse" />
      </div>
    );
  }

  const generatedDate = new Date(report.generatedAt);
  const generatedAtLabel = isNaN(generatedDate.getTime())
    ? "—"
    : generatedDate.toLocaleString("en-PK", { dateStyle: "medium", timeStyle: "short" });

  const reportModel = {
    ...report,
    reportId: report.reportId || generateReportId(generatedDate),
    generatedAtLabel,
  };

  const reportText = buildReportText(reportModel);

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(reportText);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      // Clipboard API can be blocked in some browsers/contexts — fail quietly.
    }
  };

  const handleDownload = () => {
    // TODO(Mohsin): replace this plain-text download with a call to a real
    // backend PDF generator (e.g. GET /api/report/:id/pdf) once available.
    // The button + click handler can stay the same; only the file source changes.
    const blob = new Blob([reportText], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${reportModel.reportId}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="max-w-5xl mx-auto px-5 md:px-8 py-14 md:py-20">
      <Badge tone="cyan">
        <FileText className="w-3.5 h-3.5" /> Report
      </Badge>
      <h1 className="mt-5 text-3xl md:text-5xl font-bold text-white tracking-tight">
        Official Safety Analysis Report
      </h1>
      <p className="mt-4 text-slate-400 max-w-2xl">
        Generated by FraudLens PK — a formal summary you can save, copy, or share with your bank, employer, or the
        authorities.
      </p>

      {/* Report meta */}
      <GlassCard className="mt-8 p-6 flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 rounded-xl bg-cyan-500/10 border border-cyan-500/20 flex items-center justify-center">
            <ShieldCheck className="w-5 h-5 text-accent" />
          </div>
          <div>
            <p className="text-sm font-semibold text-white">Report ID: {reportModel.reportId}</p>
            <p className="text-xs text-slate-500">Generated {generatedAtLabel}</p>
          </div>
        </div>
        <div className="flex gap-3 flex-wrap">
          <Button variant="outline" className="px-4 py-2.5 text-sm" onClick={handleCopy}>
            {copied ? <Check className="w-4 h-4" /> : <Copy className="w-4 h-4" />}
            {copied ? "Copied" : "Copy Report"}
          </Button>
          <Button className="px-4 py-2.5 text-sm" onClick={handleDownload}>
            <Download className="w-4 h-4" /> Download Report
          </Button>
        </div>
      </GlassCard>

      {/* Analyzed content */}
      <GlassCard className="mt-6 p-6">
        <p className="text-sm font-semibold text-white mb-3">Analyzed Content</p>
        <p className="text-sm text-slate-300 leading-relaxed border-l-2 border-cyan-500/30 pl-4 italic">
          {reportModel.scannedText || "No content was provided for this analysis."}
        </p>
      </GlassCard>

      {/* Findings — reuses the exact same result cards as the Result Screen */}
      <div className="mt-10">
        <h2 className="text-xl font-bold text-white mb-6">Findings</h2>
        <div className="grid md:grid-cols-2 gap-5">
          <RiskScoreCard level={reportModel.riskLevel} score={reportModel.riskScore} />
          <div className="grid grid-cols-2 gap-5">
            <ScamTypeCard type={reportModel.scamType} />
            <ConfidenceCard confidence={reportModel.confidence} />
          </div>
          <RedFlagsCard flags={reportModel.redFlags} />
          <EnglishExplanationCard text={reportModel.english} />
          <UrduExplanationCard text={reportModel.urdu} />
          <SafeActionsCard actions={reportModel.safeActions} />
          <DoNotDoCard items={reportModel.doNot} />
          <AttackChainCard steps={reportModel.attackChain} />
          <PrivacyWarningCard />
        </div>
      </div>
    </div>
  );
}
