// Frontend-only hand-off between the Result Screen and the Report Page.
//
// TODO(Mohsin — backend/API integration):
// Once /api/analyze (and a future /api/report) exist, this module is the
// only place that needs to change. Two options once a backend exists:
//   1. Keep saveReportToSession/getReportFromSession as a client-side cache,
//      but populate it from the real /api/analyze response instead of the
//      dummy analyzeText() result — no shape change needed, since the mock
//      result (see lib/analyzeText.js) already matches the fields used here.
//   2. Or fetch a saved report directly by id from something like
//      GET /api/report/:id and drop sessionStorage entirely.
// ReportView.jsx does not need to change either way, as long as the object
// passed in has the same fields as buildReportModel() below expects.

const STORAGE_KEY = "fraudlens_report";

/**
 * Save the current analysis result (+ the text that was analyzed) so the
 * Report page can read it after navigation.
 */
export function saveReportToSession(analysis, scannedText) {
  if (typeof window === "undefined" || !analysis) return;
  try {
    const payload = {
      ...analysis,
      scannedText: scannedText || "",
      generatedAt: new Date().toISOString(),
    };
    window.sessionStorage.setItem(STORAGE_KEY, JSON.stringify(payload));
  } catch (err) {
    // sessionStorage can be unavailable (e.g. private browsing) — safe to ignore,
    // the Report page will just fall back to mock data.
  }
}

/** Read back whatever was last saved by saveReportToSession(). */
export function getReportFromSession() {
  if (typeof window === "undefined") return null;
  try {
    const raw = window.sessionStorage.getItem(STORAGE_KEY);
    return raw ? JSON.parse(raw) : null;
  } catch (err) {
    return null;
  }
}

/** Generates a short, human-friendly dummy report ID (e.g. FL-260712-8341). */
export function generateReportId(date = new Date()) {
  const y = String(date.getFullYear()).slice(2);
  const m = String(date.getMonth() + 1).padStart(2, "0");
  const d = String(date.getDate()).padStart(2, "0");
  const rand = Math.floor(1000 + Math.random() * 9000);
  return `FL-${y}${m}${d}-${rand}`;
}

/**
 * Builds a plain-text version of the report, used for both the
 * "Copy Report" and "Download Report" actions.
 */
export function buildReportText(report) {
  if (!report) return "";
  const lines = [
    "FRAUDLENS PK — OFFICIAL SAFETY ANALYSIS REPORT",
    `Report ID: ${report.reportId}`,
    `Generated: ${report.generatedAtLabel}`,
    "",
    "ANALYZED CONTENT",
    report.scannedText || "(no content provided)",
    "",
    "RISK ASSESSMENT",
    `Risk Level: ${report.riskLevel}`,
    `Risk Score: ${report.riskScore}%`,
    `Scam Type: ${report.scamType}`,
    `Confidence: ${report.confidence}%`,
    "",
    "RED FLAGS",
    ...report.redFlags.map((f) => `- ${f}`),
    "",
    "ENGLISH EXPLANATION",
    report.english,
    "",
    "ROMAN URDU EXPLANATION",
    report.urdu,
    "",
    "SAFE ACTIONS",
    ...report.safeActions.map((a) => `- ${a}`),
    "",
    "DO NOT",
    ...report.doNot.map((a) => `- ${a}`),
    "",
    "ATTACK CHAIN",
    report.attackChain.join(" -> "),
    "",
    "This report was generated by FraudLens PK, a demo scam-detection tool.",
    "No personal data was stored or transmitted to any server.",
  ];
  return lines.join("\n");
}
